/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Dibujo.TableroGrafico;
import control.Control;
import control.IControl;
/**
 * Clase que representa el juego.
 * @author Equipo1.
 */
public class FJuego extends javax.swing.JFrame {

    private static FJuego instanceFJuego;
    private int tamaño;
    private IControl control;

    /**
     * Creates new form FLobbyHost
     */
    private FJuego() {
        initComponents();
//        this.partida = Partida.getPartida();
//        this.tamaño = partida.getTamañoTablero();
        this.control = Control.getControl();
        this.tamaño = this.control.getTamañoTablero();
        TableroGrafico tablero2 = new TableroGrafico(tamaño);
        getContentPane().add(tablero2);
        tablero2.setBounds(0, 0, 600, 600);
        LNombreJugador.setText(control.getTurno().getJugador().getNombre());
    }

    public static FJuego getFJuego() {
        if (instanceFJuego == null) {
            instanceFJuego = new FJuego();
        }
        return instanceFJuego;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LNombreJugador = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fichaRestantes = new javax.swing.JLabel();
        LMontoActual1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fichasEnjuego = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lanzar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        fichas = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        datoJugador = new javax.swing.JPanel();
        MontoTitulo = new javax.swing.JLabel();
        lTotalJugadores = new javax.swing.JLabel();
        MontoTitulo2 = new javax.swing.JLabel();
        MontoTitulo1 = new javax.swing.JLabel();
        LPena1 = new javax.swing.JLabel();
        lTamañoTableroi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego");
        setMinimumSize(new java.awt.Dimension(1268, 640));
        getContentPane().setLayout(null);

        tablero.setBackground(new java.awt.Color(204, 204, 204));
        tablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablero.setMinimumSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        getContentPane().add(tablero);
        tablero.setBounds(0, 0, 600, 0);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Turno  Actual");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 160, 20);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Jugador");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 90, 21);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Fichas Actuales");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 200, 160, 19);

        LNombreJugador.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LNombreJugador.setText("VACIO");
        jPanel1.add(LNombreJugador);
        LNombreJugador.setBounds(160, 70, 80, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Monto Actual");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 110, 120, 21);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel8.setText("Turno ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 10, 35, 16);

        jLabel9.setText("Jugador");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 50, 60, 16);

        jLabel10.setText("Fichas en Juego");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 110, 100, 16);

        jLabel11.setText("jLabel4");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(120, 50, 41, 16);

        jLabel12.setText("jLabel4");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(120, 110, 41, 16);

        jLabel13.setText("Monto Actual");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 80, 70, 16);

        jLabel14.setText("jLabel4");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(120, 80, 41, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 600, 240, 170);

        fichaRestantes.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        fichaRestantes.setText("VACIO");
        jPanel1.add(fichaRestantes);
        fichaRestantes.setBounds(160, 200, 70, 19);

        LMontoActual1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LMontoActual1.setText("VACIO");
        jPanel1.add(LMontoActual1);
        LMontoActual1.setBounds(160, 110, 42, 19);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Fichas En Juego");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 160, 19);

        fichasEnjuego.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        fichasEnjuego.setText("0");
        jPanel1.add(fichasEnjuego);
        fichasEnjuego.setBounds(160, 160, 70, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1000, 0, 250, 240);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        lanzar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lanzar.setText("Lanzar");
        lanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarActionPerformed(evt);
            }
        });
        jPanel3.add(lanzar);
        lanzar.setBounds(70, 70, 110, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(1000, 240, 250, 190);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jButton1.setText("Salir Partida");
        jPanel4.add(jButton1);
        jButton1.setBounds(1120, 490, 110, 40);

        jButtonSalir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir Partida");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonSalir);
        jButtonSalir.setBounds(50, 80, 140, 40);

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel16.setText("Desea abondonar juego");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(30, 20, 200, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(1000, 430, 250, 170);

        fichas.setBackground(new java.awt.Color(255, 255, 255));
        fichas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fichas.setPreferredSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout fichasLayout = new javax.swing.GroupLayout(fichas);
        fichas.setLayout(fichasLayout);
        fichasLayout.setHorizontalGroup(
            fichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        fichasLayout.setVerticalGroup(
            fichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(fichas);
        fichas.setBounds(620, 240, 350, 0);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(460, 380, 0, 2);

        datoJugador.setBackground(new java.awt.Color(204, 204, 204));
        datoJugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        datoJugador.setLayout(null);
        getContentPane().add(datoJugador);
        datoJugador.setBounds(600, 0, 400, 0);

        MontoTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MontoTitulo.setText("Total Jugadores;");
        getContentPane().add(MontoTitulo);
        MontoTitulo.setBounds(610, 80, 210, 40);

        lTotalJugadores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lTotalJugadores.setText("VACIO");
        getContentPane().add(lTotalJugadores);
        lTotalJugadores.setBounds(840, 90, 120, 30);

        MontoTitulo2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MontoTitulo2.setText("Penalización En Juego;");
        getContentPane().add(MontoTitulo2);
        MontoTitulo2.setBounds(610, 40, 210, 40);

        MontoTitulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MontoTitulo1.setText("Tamaño Tablero");
        getContentPane().add(MontoTitulo1);
        MontoTitulo1.setBounds(610, 0, 170, 60);

        LPena1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LPena1.setText("VACIO");
        getContentPane().add(LPena1);
        LPena1.setBounds(840, 50, 120, 30);

        lTamañoTableroi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lTamañoTableroi.setText("VACIO");
        getContentPane().add(lTamañoTableroi);
        lTamañoTableroi.setBounds(840, 20, 110, 22);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void lanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarActionPerformed

        //Aun no implementado se prente realizar cuando tengamos en claro la arquitectura.
        
    }//GEN-LAST:event_lanzarActionPerformed


    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FValidacion().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LMontoActual1;
    public static javax.swing.JLabel LNombreJugador;
    public static javax.swing.JLabel LPena1;
    private javax.swing.JLabel MontoTitulo;
    private javax.swing.JLabel MontoTitulo1;
    private javax.swing.JLabel MontoTitulo2;
    private javax.swing.JPanel datoJugador;
    public static javax.swing.JLabel fichaRestantes;
    private javax.swing.JPanel fichas;
    public static javax.swing.JLabel fichasEnjuego;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lTamañoTableroi;
    public static javax.swing.JLabel lTotalJugadores;
    private javax.swing.JButton lanzar;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
